export const ADD_CONSTRUCTOR__BUN = "GET_CONSTRUCTOR_BUN";
export const ADD_TO_CONSTRUCTOR_INGREDIENTS_LIST =
  "ADD_TO_CONSTRUCTOR_INGREDIENTS_LIST";
export const DELETE_FROM_CONSTRUCTOR_INGREDIENTS_LIST =
  "DELETE_FROM_CONSTRUCTOR_INGREDIENTS_LIST";
export const SET_ORDER_OF_INGREDIENTS = "SET_ORDER_OF_INGREDIENTS";
