export const WS_FEED_CONNECTION_START: "WS_FEED_CONNECTION_START" =
  "WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS" =
  "WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR" =
  "WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED" =
  "WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SET_MESSAGE: "WS_FEED_SET_MESSAGE" = "WS_FEED_SET_MESSAGE";

export const wsActionsFeed = {
  wsInit: WS_FEED_CONNECTION_START,
  onOpen: WS_FEED_CONNECTION_SUCCESS,
  onMessage: WS_FEED_GET_MESSAGE,
  onClose: WS_FEED_CONNECTION_CLOSED,
  onError: WS_FEED_CONNECTION_ERROR,
  wsSendMessage: WS_FEED_SET_MESSAGE,
};
