export const WS_PROFILE_FEED_CONNECTION_START: "WS_PROFILE_FEED_CONNECTION_START" =
  "WS_PROFILE_FEED_CONNECTION_START";
export const WS_PROFILE_FEED_CONNECTION_SUCCESS: "WS_PROFILE_FEED_CONNECTION_SUCCESS" =
  "WS_PROFILE_FEED_CONNECTION_SUCCESS";
export const WS_PROFILE_FEED_CONNECTION_ERROR: "WS_PROFILE_FEED_CONNECTION_ERROR" =
  "WS_PROFILE_FEED_CONNECTION_ERROR";
export const WS_PROFILE_FEED_CONNECTION_CLOSED: "WS_PROFILE_FEED_CONNECTION_CLOSED" =
  "WS_PROFILE_FEED_CONNECTION_CLOSED";
export const WS_PROFILE_FEED_GET_MESSAGE: "WS_PROFILE_FEED_GET_MESSAGE" =
  "WS_PROFILE_FEED_GET_MESSAGE";
export const WS_PROFILE_FEED_SET_MESSAGE: "WS_PROFILE_FEED_SET_MESSAGE" =
  "WS_PROFILE_FEED_SET_MESSAGE";
